# Generated by Django 4.2.7 on 2023-11-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contact_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_models',
            new_name='Contact',
        ),
    ]
